[package]
name = "near-structs-checker"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Structs checker"
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
near-structs-checker-core = { path = "../structs-checker-core" }

quote = { workspace = true, optional = false }
syn = { workspace = true, optional = false }
serde_json = { workspace = true, features = ["preserve_order"], optional = false }
serde = { workspace = true, optional = false }
inventory = { workspace = true, optional = false }
proc-macro2 = "1.0.86"

[features]
#check_protocol_structs = ["inventory", "quote"]
