[package]
name = "near-structs-checker"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "ProtocolStruct macro implementation to check integrity of the protocol structs"
repository.workspace = true
license.workspace = true
publish = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
syn = { workspace = true, optional = true }

[dev-dependencies]
near-structs-checker-core = { path = "../structs-checker-core" }

[features]
protocol_schema = [
  "near-structs-checker-core/protocol_schema",
  "proc-macro2",
  "syn",
  "quote"
]
