[package]
name = "near-o11y"
version = "0.0.0"
authors.workspace = true
publish = true
rust-version.workspace = true
edition.workspace = true
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/near/nearcore"
description = "Observability helpers for the near codebase"

[dependencies]
<<<<<<< HEAD
atty = "0.2"
backtrace = "0.3.64"
clap = { version = "3", features = ["derive"] }
once_cell = "1.5.2"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
thiserror = "1"
tokio = { version = "1.16", features = ["rt-multi-thread"]}
tracing = { version = "0.1.13", features = ["std"] }
tracing-appender = "0.2.2"
tracing-opentelemetry = { version = "0.17" }
tracing-serde = "0.1"
tracing-subscriber = { version = "0.3.9", features = ["fmt", "env-filter", "registry", "std"] }
chrono = "0.4.19"
serde_json = "1"
=======
near-crypto = { path = "../../core/crypto" }
near-primitives-core = { path = "../../core/primitives-core" }

actix.workspace = true
atty.workspace = true
backtrace.workspace = true
clap.workspace = true
once_cell.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
prometheus.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
bencher.workspace = true
itoa.workspace = true
smartstring.workspace = true

[features]
io_trace = []

[[bench]]
name = "metrics"
harness = false
>>>>>>> master
