[package]
name = "protocol-schema-check"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
near-structs-checker.workspace = true
near-structs-checker-core.workspace = true
near-primitives.workspace = true

serde_json = { workspace = true, features = ["preserve_order"] }
inventory.workspace = true
toml.workspace = true

[features]
protocol_schema = [
  "near-structs-checker/protocol_schema",
  "near-structs-checker-core/protocol_schema",
  "near-primitives/protocol_schema",
]
