[package]
name = "protocol-schema-check"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
near-structs-checker.workspace = true
near-structs-checker-core.workspace = true
near-primitives.workspace = true

serde_json = { workspace = true, features = ["preserve_order"] }
inventory = { workspace = true, optional = true }
toml.workspace = true

[features]
default = [
  "inventory",
  "near-structs-checker/protocol_schema",
  "near-structs-checker-core/protocol_schema",
  "near-primitives/protocol_schema",
]
