[package]
name = "near-store"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors.workspace = true
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version.workspace = true
edition.workspace = true

[dependencies]
<<<<<<< HEAD
byteorder = "1.2"
bytesize = { version = "1.1", features = ["serde"] }
derive_more = "0.99.3"
elastic-array = "0.11"
enum-map = "2.1.0"
rocksdb = { version = "0.18.0", default-features = false, features = ["snappy", "lz4", "zstd", "zlib"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
num_cpus = "1.11"
rand = "0.7"
strum = { version = "0.24", features = ["derive"] }
fs2 = "0.4"
tracing = "0.1.13"
borsh = "0.9"
thiserror = "1"
lru = "0.7.2"
once_cell = "1.5.2"
rlimit = "0.7"
atomic_refcell = "0.1.8"
=======
anyhow.workspace = true
borsh.workspace = true
byteorder.workspace = true
bytesize.workspace = true
crossbeam.workspace = true
derive_more.workspace = true
elastic-array.workspace = true
enum-map.workspace = true
fs2.workspace = true
itoa.workspace = true
lru.workspace = true
num_cpus.workspace = true
once_cell.workspace = true
rand.workspace = true
rlimit.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
>>>>>>> master

near-crypto = { path = "../crypto" }
near-o11y = { path = "../o11y" }
near-primitives = { path = "../primitives" }

[dev-dependencies]
assert_matches.workspace = true
bencher.workspace = true
insta.workspace = true
rand.workspace = true

[[bench]]
name = "trie_bench"
harness = false

[[bench]]
name = "store_bench"
harness = false

[features]
default = []
io_trace = []
no_cache = []
single_thread_rocksdb = [] # Deactivate RocksDB IO background threads
test_features = []
protocol_feature_flat_state = []

nightly_protocol = []
nightly = [
  "nightly_protocol",
]
