[package]
name = "near-structs-checker-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
inventory = { workspace = true, optional = true }

[features]
protocol_schema = ["inventory"]
